# Generated by Django 5.2.7 on 2025-11-16 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1-based index of the chain item within the session')),
                ('value', models.CharField(help_text="chain step, e.g. 'rock', 'paper', 'scissors'", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_entries', to='game.gamesession')),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', 'recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'created_at'], name='game_gamese_user_id_54111f_idx'),
        ),
        migrations.AddIndex(
            model_name='chainentry',
            index=models.Index(fields=['session', 'position'], name='game_chaine_session_ba5a93_idx'),
        ),
        migrations.AddIndex(
            model_name='chainentry',
            index=models.Index(fields=['value'], name='game_chaine_value_789751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chainentry',
            unique_together={('session', 'position')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['-points'], name='game_score_points_0ff2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user'], name='game_score_user_id_030cca_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['recorded_at'], name='game_score_recorde_3fb75c_idx'),
        ),
    ]
